services:
  yew_front:
    image: ghcr.io/juliog922/yew_front:latest
    command: trunk serve --release --port 8092 --address 0.0.0.0 --no-autoreload
    networks:
      - app_network
    deploy:
      update_config:
        order: start-first

  actix_api:
    image: ghcr.io/juliog922/actix_api:latest
    command: cargo run --bin server --release
    environment:
      - API_PORT=8080
      - API_HOST=0.0.0.0
    networks:
      - app_network
    deploy:
      update_config:
        order: start-first

  nginx:
    image: ghcr.io/juliog922/nginx:latest
    ports:
      - "8091:80"
    networks:
      - app_network
    deploy:
      update_config:
        order: start-first

networks:
  app_network:
    driver: overlay