services:
  yew_front:
    build:
      context: ./yew_front
    expose:
      - "8092"
    volumes:
      - ./yew_front:/app
    command: trunk serve --release --port 8092 --address 0.0.0.0 --no-autoreload
    networks:
      - app_network
    restart: always

  actix_api:
    build:
      context: ./actix_api
    expose:
      - "8080"
    volumes:
      - ./actix_api:/app
    command: cargo run --bin server --release
    environment:
      - API_PORT=8080
      - API_HOST=0.0.0.0
    networks:
      - app_network
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "8091:80"
    networks:
      - app_network
    depends_on:
      - yew_front
      - actix_api
    restart: always

networks:
  app_network:
    driver: bridge