services:
  yew_front:
    image: ghcr.io/juliog922/yew_front:latest
    command: trunk serve --release --port 8092 --address 0.0.0.0 --no-autoreload
    networks:
      - app_network
    restart: always

  actix_api:
    image: ghcr.io/juliog922/actix_api:latest
    command: cargo run --bin server --release
    environment:
      - API_PORT=8080
      - API_HOST=0.0.0.0
    networks:
      - app_network
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "8091:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - yew_front
      - actix_api
    restart: always

networks:
  app_network:
    driver: bridge