-- Add up migration script here
CREATE TABLE IF NOT EXISTS tapi_uris (
    id SERIAL PRIMARY KEY,
    uri VARCHAR UNIQUE NOT NULL,
    request_method VARCHAR NOT NULL,
    topic VARCHAR UNIQUE NOT NULL,
    dependency VARCHAR
);

INSERT INTO tapi_uris (uri, request_method, topic, dependency) VALUES
    ('/.well-known/host-meta', 'GET', 'host-meta', NULL),
    ('/ietf-yang-library:modules-state/module', 'GET', 'module', NULL),
    ('/ietf-restconf-monitoring:restconf-state/streams', 'GET', 'streams', NULL),
    ('/ietf-restconf-monitoring:restconf-state/capabilities', 'GET', 'capabilities', NULL),
    ('/tapi-common:context', 'GET', 'context', NULL),
    ('/tapi-common:context?depth=3', 'GET', 'context.depth=3', NULL),
    ('/tapi-common:context?fields=name;uuid', 'GET', 'context.name;uuid', NULL),  
    ('/tapi-common:context/service-interface-point', 'GET', 'services', NULL),
    ('/tapi-common:context?fields=service-interface-point(uuid)', 'GET', 'services.uuid-list', NULL),
    ('/tapi-common:context/service-interface-point={uuid}', 'GET', 'services.by-parts', 'services.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context', 'GET', 'topology', NULL),
    ('/tapi-common:context/tapi-topology:topology-context/nw-topology-service', 'GET', 'nw-topology', NULL),
    ('/tapi-common:context/tapi-topology:topology-context/nw-topology-service?fields=topology(uuid)', 'GET', 'nw-topology.uuid-list', NULL),
    ('/tapi-common:context/tapi-topology:topology-context?fields=topology(uuid)', 'GET', 'topology.uuid-list', NULL),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}', 'GET', 'topology.by-parts', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}?depth=3', 'GET', 'topology.by-parts.depth=3', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}?fields=uuid;name;layer-protocol-name', 'GET', 'topology.uuid;name;layer-protocol-name', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/node', 'GET', 'node', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}?fields=node(uuid)', 'GET', 'node.uuid-list', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/node={uuid}', 'GET', 'node.by-parts', 'node.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/link', 'GET', 'link', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}?fields=link(uuid)', 'GET', 'link.uuid-list', 'topology.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/link={uuid}', 'GET', 'link.by-parts', 'link.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/node={uuid}?fields=owned-node-edge-point(uuid)', 'GET', 'node.owned-node-edge-point.uuid-list', 'node.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/node={uuid}/owned-node-edge-point={uuid}', 'GET', 'node.owned-node-edge-point.by-parts', 'node.owned-node-edge-point.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/node={uuid}/owned-node-edge-point={uuid}/tapi-connectivity:cep-list', 'GET', 'node.owned-node-edge-point.cep-list', 'node.owned-node-edge-point.uuid-list'),
    ('/tapi-common:context/tapi-topology:topology-context/topology={uuid}/node={uuid}/owned-node-edge-point={uuid}/tapi-connectivity:cep-list/connection-end-point={uuid}', 'GET', 'node.owned-node-edge-point.cep-list.connection-end-point.by-parts', '?'),
    ('/tapi-common:context/tapi-connectivity:connectivity-context', 'GET', 'connectivity-context' , NULL),
    ('/tapi-common:context/tapi-connectivity:connectivity-context?fields=connectivity-service(uuid)', 'GET', 'connectivity-service.uuid-list', NULL),
    ('/tapi-common:context/tapi-connectivity:connectivity-context/connectivity-service={uuid}', 'GET', 'connectivity-service.by-parts', 'connectivity-service.uuid-list'),
    ('/tapi-common:context/tapi-connectivity:connectivity-context?fields=connection(uuid)', 'GET', 'connection.uuid-list', NULL),
    ('/tapi-common:context/tapi-connectivity:connectivity-context/connection={uuid}', 'GET', 'connection.by-parts', 'connection.uuid-list'),
    ('/tapi-common:context/tapi-connectivity:connectivity-context/connectivity-service={uuid}?fields=connection(connection-uuid)', 'GET', 'connection.connection-uuid-list', 'connectivity-service.uuid-list'),
    ('/tapi-common:context/tapi-equipment:physical-context', 'GET', 'physical-context', NULL),
    ('/tapi-common:context/tapi-equipment:physical-context?fields=device(uuid)', 'GET', 'device.uuid-list', NULL),
    ('/tapi-common:context/tapi-equipment:physical-context/device={uuid}', 'GET', 'device.by-parts', 'device.uuid-list'),
    ('/tapi-common:context/tapi-equipment:physical-context?fields=physical-span(uuid)', 'GET', 'physical-span.uuid-list', NULL),
    ('/tapi-common:context/tapi-equipment:physical-context/physical-span={uuid}', 'GET', 'physical-span.by-parts', 'physical-span.uuid-list'),
    ('/tapi-common:context/tapi-equipment:physical-context/device={uuid}?fields=equipment(uuid)', 'GET', 'equipment.uuid-list', 'device.uuid-list'),
    ('/tapi-common:context/tapi-equipment:physical-context/device={uuid}/equipment={uuid}', 'GET', 'equipment.by-parts', 'device.uuid-list'),
    ('/tapi-common:context/tapi-path-computation:path-computation-context', 'GET', 'path-computation-context', NULL),
    ('/tapi-common:context/tapi-path-computation:path-computation-context/path-comp-service={uuid}', 'GET', 'path-comp-service.by-parts', '?'),
    ('/tapi-common:context/tapi-path-computation:path-computation-context/path-comp-service={uuid}?fields=path(path-uuid)', 'GET', 'path.path-uuid-list', '?'),
    ('/tapi-common:context/tapi-path-computation:path-computation-context/path-comp-service={uuid}/path', 'GET', 'path', '?'),
    ('/tapi-common:context/tapi-path-computation:path-computation-context/path={uuid}', 'GET', 'path.by-parts', '?'),
    ('/tapi-common:context/tapi-notification:notification-context', 'GET', 'notification-context', NULL),
    ('/tapi-common:context/tapi-notification:notification-context/notif-subscription={uuid}', 'GET', 'notif-subscription.by-parts', '?'),
    ('/tapi/data/context/stream-context/available-stream', 'GET', 'available-stream', NULL),
    ('/tapi/data/context/stream-context/supported-stream-type', 'GET', 'supported-stream-type', NULL),
    ('/tapi-common:context/tapi-streaming:stream-context', 'GET', 'stream-context', NULL),
    ('/tapi-common:context/tapi-streaming:stream-context/available-stream', 'GET', 'stream-context.available-stream', NULL),
    ('/restconf/data/tapi-common:context/tapi-streaming:stream-context/supported-stream-type', 'GET', 'stream-context.supported-stream-type', NULL)
ON CONFLICT(uri) DO NOTHING;