name: pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run Cargo Test in actix_api
        run: |
          cargo test -p actix_api

  build-and-test-images:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build yew_front Image
        id: build_yew_front
        uses: docker/build-push-action@v6
        with:
          context: ./yew_front
          file: ./yew_front/Dockerfile
          push: false
          tags: yew_front:latest

      - name: Build actix_api Image
        id: build_actix_api
        uses: docker/build-push-action@v6
        with:
          context: ./actix_api
          file: ./actix_api/Dockerfile
          push: false
          tags: actix_api:latest

      - name: Build nginx Image
        id: build_nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: false
          tags: nginx:latest

      - name: Push yew_front Image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./yew_front
          file: ./yew_front/Dockerfile
          push: true
          tags: |
            ghcr.io/juliog922/yew_front:latest
            ghcr.io/juliog922/yew_front:${{ github.sha }}

      - name: Push actix_api Image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./actix_api
          file: ./actix_api/Dockerfile
          push: true
          tags: |
            ghcr.io/juliog922/actix_api:latest
            ghcr.io/juliog922/actix_api:${{ github.sha }}

      - name: Push nginx Image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ghcr.io/juliog922/nginx:latest
            ghcr.io/juliog922/nginx:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs:
      - build-and-test-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Stack Deploy
        run: |
          docker --context testing stack deploy -c compose.yml tapi --with-registry-auth
