name: pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  packages: write

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run Cargo Test in actix_api
        run: |
          cargo test -p actix_api

  build-and-push-images:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push yew_front Image
        uses: docker/build-push-action@v6
        with:
          context: ./yew_front
          file: ./yew_front/Dockerfile
          push: true
          tags: |
            ghcr.io/juliog922/yew_front:latest
            ghcr.io/juliog922/yew_front:${{ github.sha }}

      - name: Build and Push actix_api Image
        uses: docker/build-push-action@v6
        with:
          context: ./actix_api
          file: ./actix_api/Dockerfile
          push: true
          tags: |
            ghcr.io/juliog922/actix_api:latest
            ghcr.io/juliog922/actix_api:${{ github.sha }}

      - name: Build and Push nginx Image
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ghcr.io/juliog922/nginx:latest
            ghcr.io/juliog922/nginx:${{ github.sha }}
  
  deploy:
    runs-on: self-hosted
    needs:
      - build-and-push-images
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: zenfulstats
        file: docker-stack.yaml
        host: zenful.site
        user: deploy
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        env_file: ./envfile


